# -*- coding: utf-8 -*-
"""Car Price Analysis Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WA2QftKjc56MCZJrcRc2Z2GaMUqUg0f6

# ***1. Data Ingestion & Quality Profiling***

### **1.1 Load & Inspect**

1.   Read car_prices.csv into a pandas DataFrame.
"""

import pandas as pd
df = pd.read_csv('/content/car_prices.csv')

# Display first 5 rows
print("First 5 Rows:")
display(df.head())

# Display data types
print(df.dtypes)

# Display record count
print('Total Records:', len(df))

"""### **1.2 Understanding the Data Structure**"""

# Check the shape of the dataset (rows and columns).
print('Dataset Shape:', df.shape)

# Display column names and data types.
print('Columns:', df.columns)

# Column datatypes and record count.
print(df.info())

"""### **1.3 Missing & Anomaly Detection**"""

# Quantify nulls per column; visualize with a bar chart or heatmap.
null_values = df.isnull().sum()
print(null_values)

import matplotlib.pyplot as plt
plt.figure(figsize=(12,6))
null_values.plot(kind='bar')
plt.title('Null Values Per Column')
plt.xlabel('Columns')
plt.ylabel('Count of Null Values')
plt.xticks(rotation=45)
plt.show()

# Quantify nulls per column
null_counts = df.isnull().sum()
null_percentages = (df.isnull().sum() / len(df)) * 100

null_info = pd.DataFrame({
    'Null Count': null_counts,
    'Null Percentage': null_percentages
}).sort_values(by='Null Count', ascending=False)

print("Null values per column:")
display(null_info[null_info['Null Count'] > 0])

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize nulls with a bar chart
plt.figure(figsize=(12, 6))
sns.barplot(x=null_info[null_info['Null Count'] > 0].index, y=null_info[null_info['Null Count'] > 0]['Null Percentage'])
plt.title('Percentage of Null Values Per Column')
plt.xlabel('Columns')
plt.ylabel('Null Percentage (%)')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Resolving Null Values
Based on the analysis of null percentages and data types, the following strategies will be applied:
- **Drop rows:** For columns `vin`, `sellingprice`, and `saledate`, which have a very small number of missing values and are critical identifiers or target variables, rows containing these nulls will be dropped.
- **Impute with mode:** For categorical columns (`transmission`, `body`, `trim`, `model`, `make`, `color`, `interior`) with missing values, the mode (most frequent value) will be used for imputation.
- **Impute with median:** For numerical columns (`condition`, `odometer`, `mmr`) with missing values, the median will be used for imputation to be robust against outliers.
"""

# Drop rows with nulls in vin, sellingprice, saledate
initial_rows = df.shape[0]
df.dropna(subset=['vin', 'sellingprice', 'saledate'], inplace=True)
print(f"Dropped {initial_rows - df.shape[0]} rows with nulls in 'vin', 'sellingprice', or 'saledate'.")

# Impute categorical columns with mode
categorical_cols_to_impute = ['transmission', 'body', 'trim', 'model', 'make', 'color', 'interior']
for col in categorical_cols_to_impute:
    if df[col].isnull().any():
        mode_value = df[col].mode()[0]
        df[col].fillna(mode_value, inplace=True)
        print(f"Imputed '{col}' with mode: {mode_value}")

# Impute numerical columns with median
numerical_cols_to_impute = ['condition', 'odometer', 'mmr']
for col in numerical_cols_to_impute:
    if df[col].isnull().any():
        median_value = df[col].median()
        df[col].fillna(median_value, inplace=True)
        print(f"Imputed '{col}' with median: {median_value}")

# Verify no more nulls
print("\nVerifying nulls after resolution:")
display(df.isnull().sum()[df.isnull().sum() > 0])

# Count number of duplicate records
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate records found: {duplicate_rows}")

# Delete duplicate records if any present
if duplicate_rows > 0:
    df.drop_duplicates(inplace=True)
    print(f"Deleted {duplicate_rows} duplicate records. New dataset shape: {df.shape}")
else:
    print("No duplicate records found.")

"""## **2. Dataframes Queries**
### 2.1 Calculate the average, minimum, and maximum car price
"""

avg_price = df['sellingprice'].mean()
min_price = df['sellingprice'].min()
max_price = df['sellingprice'].max()

print(f"Average Car Price: ${avg_price:,.2f}")
print(f"Minimum Car Price: ${min_price:,.2f}")
print(f"Maximum Car Price: ${max_price:,.2f}")

"""### **2.2 List all unique colors of cars**"""

print(df['color'].unique())

# List all unique colors of cars
unique_colors = df['color'].unique()
print("Unique car colors:")
for color in unique_colors:
    print(f"- {color}")

"""### **2.3 Find the number of unique car brands and car models**"""

# Find the number of unique car brands (make)
unique_makes = df['make'].nunique()
print(f"Number of unique car brands: {unique_makes}")

# Find the number of unique car models
unique_models = df['model'].nunique()
print(f"Number of unique car models: {unique_models}")

"""### **2.4 Find all car information having selling prices greater than $165000**"""

# Find all car information having selling prices greater than $165000
high_price_cars = df[df['sellingprice'] > 165000]

print(f"Number of cars with selling price greater than $165,000: {len(high_price_cars)}")
print("Car information for vehicles with selling price > $165,000:")
display(high_price_cars)

"""### ***2.5 Find the top 5 most frequently sold car models?***"""

#Find the top 5 most frequently sold car models?
top_5_models = df['model'].value_counts().head(5)
print("Top 5 most frequently sold car models:")
display(top_5_models)

"""### **2.6 Average selling price by brand (make)**

"""

average_price_by_make = df.groupby('make')['sellingprice'].mean().sort_values(ascending=False)
print("Average selling price by brand:")
display(average_price_by_make)

"""### **2.7 Minimum selling price of cars for each interior**"""

min_price_by_interior = df.groupby('interior')['sellingprice'].min().sort_values()
print("Minimum selling price by interior:")
display(min_price_by_interior)

"""### **2.8 Find highest odometer reading per year from highest to lowest order?**"""

highest_odometer_per_year = df.groupby('year')['odometer'].max().sort_values(ascending=False)
print("Highest odometer reading per year (from highest to lowest):")
display(highest_odometer_per_year)

"""### **2.9 Create a new column for car age (assuming the current year is 2025)**"""

##Create a new column for car age (assuming the current year is 2025)
df['car_age'] = 2025 - df['year']
print("DataFrame with new 'car_age' column:")
display(df[['year', 'car_age']].head())

"""# **2.10 Find the number of cars having a condition greater than or equal to 48 and odometer greater than 90000?**"""

filtered_cars =  df[(df['condition'] >= 48) & (df['odometer'] > 90000)]

print('Count:', len(filtered_cars))

filtered_cars = df[(df['condition'] >= 48) & (df['odometer'] > 90000)]
num_filtered_cars = len(filtered_cars)
print(f"Number of cars with condition >= 48 and odometer > 90000: {num_filtered_cars}")

"""### **2.11 Which state consistently has higher car prices for newe cars(year>2013)**

"""

newer_cars = df[df['year'] > 2013]

state_price = newer_cars.groupby('state')['sellingprice'].mean().sort_values(ascending=False)

print(state_price)

"""# **2.12 For cars with excellent condition (top 20%), which makes have the lowest average price (value for money)?**:  """

threshold = df['condition'].quantile(0.80)

excellent_cars = df[df['condition'] >= threshold]

best_value = excellent_cars.groupby('make')['sellingprice'].mean().sort_values()

print(best_value.head(10))

"""# **3. Data Visualization and insights:**

**3.1 Show the correlation of all the features(columns) having numerical
values(e.g. selling price, odometer).**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select only numerical columns for correlation analysis
numerical_df = df.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numerical_df.corr()

# Plotting the heatmap
plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""**Insight:**


*   Selling price generally decreases with higher odometer readings.
*   Newer cars tend to have higher selling prices.
* Condition score positively impacts selling price.

**3.1 Visualize the distribution of selling prices, odometer readings, and car age using histograms or density plots.**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set up the matplotlib figure and axes
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Plotting Selling Price Distribution
sns.histplot(df['sellingprice'], kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Distribution of Selling Price')
axes[0].set_xlabel('Selling Price')
axes[0].set_ylabel('Frequency')

# Plotting Odometer Readings Distribution
sns.histplot(df['odometer'], kde=True, ax=axes[1], color='lightcoral')
axes[1].set_title('Distribution of Odometer Readings')
axes[1].set_xlabel('Odometer')
axes[1].set_ylabel('Frequency')

# Plotting Car Age Distribution
sns.histplot(df['car_age'], kde=True, ax=axes[2], color='lightgreen')
axes[2].set_title('Distribution of Car Age')
axes[2].set_xlabel('Car Age')
axes[2].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

"""**Insight:**
* Newer model cars generally have higher selling prices.
* Older vehicles show significant depreciation.

**3.1 Analyze the relationship between 'sellingprice' and other key features like 'odometer', 'condition', and 'car_age' using scatter plots.**
"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(20, 6))

# Scatter plot: Selling Price vs. Odometer
sns.scatterplot(data=df, x='odometer', y='sellingprice', ax=axes[0], alpha=0.6)
axes[0].set_title('Selling Price vs. Odometer')
axes[0].set_xlabel('Odometer')
axes[0].set_ylabel('Selling Price')

# Scatter plot: Selling Price vs. Condition
sns.scatterplot(data=df, x='condition', y='sellingprice', ax=axes[1], alpha=0.6)
axes[1].set_title('Selling Price vs. Condition')
axes[1].set_xlabel('Condition')
axes[1].set_ylabel('Selling Price')

# Scatter plot: Selling Price vs. Car Age
sns.scatterplot(data=df, x='car_age', y='sellingprice', ax=axes[2], alpha=0.6)
axes[2].set_title('Selling Price vs. Car Age')
axes[2].set_xlabel('Car Age')
axes[2].set_ylabel('Selling Price')

plt.tight_layout()
plt.show()

"""**1. Selling Price vs Odometer**
* Cars with lower odometer readings have higher selling prices.
* Selling price decreases as mileage increases.
* High mileage cars usually have lower resale value.

**2. Selling Price vs Condition**
* Cars with better condition scores have higher selling prices.
* Poor condition cars are sold at lower prices.
* Good condition increases resale value.

**3. Selling Price vs Car Age**
* Newer cars have higher selling prices.
* Older cars have lower selling prices.
* Selling price decreases as car age increases due to depreciation.

** Overall Observation**
* Low mileage + good condition + newer cars = higher selling price.
* High mileage + old cars + poor condition = lower selling price.

#**3.2 Plot a graph to show the average selling price by year and explain the pattern you notice from the graph. Which plot will you use bar or scatter?**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the average selling price by year
avg_selling_price_by_year = df.groupby('year')['sellingprice'].mean().reset_index()

# Create the bar plot
plt.figure(figsize=(15, 7))
sns.barplot(x='year', y='sellingprice', data=avg_selling_price_by_year, palette='viridis')
plt.title('Average Selling Price by Year')
plt.xlabel('Year')
plt.ylabel('Average Selling Price')
plt.xticks(rotation=90) # Rotate x-axis labels for better readability
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""# **3.3 Plot a graph to show average selling price by odometer and explain the trend you notice from the graph.**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.regplot(data=df, x='odometer', y='sellingprice', scatter_kws={'alpha':0.3}, line_kws={'color':'red'})
plt.title('Average Selling Price vs. Odometer with Regression Line')
plt.xlabel('Odometer')
plt.ylabel('Selling Price')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""#3.3 Average Selling Price by Odometer"""

odometer_bins = pd.cut(df['odometer'], bins=10)

avg_price_odometer = df.groupby(odometer_bins, observed=False)['sellingprice'].mean()

plt.figure(figsize=(12,6))
avg_price_odometer.plot(kind='line', marker='o')
plt.title('Average Selling Price by Odometer')
plt.xlabel('Odometer Range')
plt.ylabel('Average Selling Price')
plt.xticks(rotation=45)
plt.show()

"""**Simple Insights from the Graph**
* Selling price decreases as odometer reading increases.
* Cars with low mileage have higher selling prices.
* High mileage cars are generally sold at lower prices.
* The red regression line shows a negative relationship between mileage and price.
* Most expensive cars are concentrated at lower odometer values.
A few outliers are present with unusual prices.

#**3.4 Plot a graph to show the number of cars sold in each state. Find the top three highest car selling states by having a look at the graph?**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the number of cars sold in each state
cars_by_state = df['state'].value_counts().reset_index()
cars_by_state.columns = ['state', 'num_cars_sold']

# Plotting the bar graph
plt.figure(figsize=(15, 7))
sns.barplot(x='state', y='num_cars_sold', data=cars_by_state, palette='viridis', hue='state', legend=False)
plt.title('Number of Cars Sold in Each State')
plt.xlabel('State')
plt.ylabel('Number of Cars Sold')
plt.xticks(rotation=90) # Rotate x-axis labels for better readability
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# To explicitly find the top 3 states:
print('\nTop 3 highest car selling states:')
display(cars_by_state.head(3))

"""**Insights for Average Selling Price by Condition Range Graph**
* Average selling price increases as the condition score increases.
C* ars in better condition have higher resale value.
* Poor condition cars are sold at lower prices.
The highest average selling price is observed in the top condition ranges (40–50).
* Condition plays an important role in determining car price.
* Buyers are willing to pay more for well-maintained vehicles.
"""

df['condition_range'] = pd.cut(df['condition'], bins=range(0, 101, 5))

condition_price = df.groupby('condition_range', observed=False)['sellingprice'].mean()

plt.figure(figsize=(15,6))
condition_price.plot(kind='bar')
plt.title('Average Selling Price by Condition Range')
plt.xlabel('Condition Range')
plt.ylabel('Average Selling Price')
plt.xticks(rotation=45)
plt.show()

"""**Insights for Number of Cars Sold in Each State Graph**
* A few states dominate the used car market.
* Florida (FL), California (CA), and Texas (TX) are the top car selling states.
* Most states have lower sales compared to the top states.
* Car sales are higher in states with larger populations and higher vehicle demand.
* The graph shows uneven distribution of car sales across states.

#**3.5 Plot a bar graph of average selling price by condition score ranges of size 5. Give a summary of the insights.**

## 3.7 Plot a graph to show the average selling price by make
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the average selling price by make
avg_selling_price_by_make = df.groupby('make')['sellingprice'].mean().sort_values(ascending=False).reset_index()

# Plotting the bar graph for the top N makes for better readability
plt.figure(figsize=(16, 8))
sns.barplot(x='make', y='sellingprice', data=avg_selling_price_by_make.head(20), palette='viridis', hue='make', legend=False)
plt.title('Top 20 Car Makes by Average Selling Price')
plt.xlabel('Car Make')
plt.ylabel('Average Selling Price')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Insights from 'Average Selling Price by Make' Graph:

This bar graph displays the average selling price for the top 20 car makes. Here are some key observations:

*   **Luxury Brands Dominate:** Brands like Rolls-Royce, Ferrari, and Lamborghini command significantly higher average selling prices, indicating their premium market positioning.
*   **Price Variation Across Brands:** There's a wide range in average selling prices, reflecting differences in brand perception, vehicle segments, features, and target demographics.
*   **Mid-Range Market:** Many popular brands fall into a mid-range average selling price bracket, catering to a broader consumer base.
*   **Insights on Value:** Brands with lower average selling prices might represent more accessible or value-oriented options in the market.

#**3.6 Plot a bar graph of no. of cars sold by condition ranges of size 10. Give some insights from the graph.**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create condition ranges of size 10
df['condition_range_10'] = pd.cut(df['condition'], bins=range(0, 101, 10), right=False)

# Count the number of cars in each condition range
cars_by_condition_range = df['condition_range_10'].value_counts().sort_index(ascending=True)

# Plotting the bar graph
plt.figure(figsize=(15, 7))
sns.barplot(x=cars_by_condition_range.index.astype(str), y=cars_by_condition_range.values, palette='viridis', hue=cars_by_condition_range.index.astype(str), legend=False)
plt.title('Number of Cars Sold by Condition Ranges (Size 10)')
plt.xlabel('Condition Range')
plt.ylabel('Number of Cars Sold')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Insights from 'Number of Cars Sold by Condition Ranges' Graph:

This bar graph illustrates the distribution of the number of cars sold across different condition score ranges (each of size 10). Here are some key insights:

*   **Concentration in Mid-Range Conditions:** A significant majority of cars sold tend to fall within the mid-range condition scores, typically between 20 and 50. This suggests that most consumers are buying cars that are neither brand new nor extremely worn.
*   **Fewer Cars at Extremes:** There are fewer cars sold at the very low (e.g., 0-10) and very high (e.g., 80-100) ends of the condition spectrum. This is expected, as extremely poor condition cars might be non-functional or salvaged, while extremely high condition cars might be rare or new, thus having fewer units available or sold in this dataset.
*   **Peak around 30-40:** The graph often shows a peak in the number of cars sold around the 30-40 condition range, indicating a sweet spot where a balance between condition and price is met for a large segment of buyers.
*   **Market for Used Cars:** The overall distribution reinforces that the dataset represents a vibrant used car market, with a strong focus on vehicles that have some wear but are still in good, usable condition.

#**3.7 Plot a box plot to show the distribution of car selling prices grouped by color. Extract insights and if required, remove outliers and plot the graph again.**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get the top 10 most frequent colors for better visualization
top_colors = df['color'].value_counts().head(10).index.tolist()
df_filtered_colors = df[df['color'].isin(top_colors)]

plt.figure(figsize=(18, 8))
sns.boxplot(x='color', y='sellingprice', data=df_filtered_colors, palette='viridis', hue='color', legend=False)
plt.title('Distribution of Car Selling Prices by Top 10 Colors')
plt.xlabel('Car Color')
plt.ylabel('Selling Price')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Insights from 'Distribution of Car Selling Prices by Top 10 Colors' Box Plot:

This box plot illustrates the distribution of car selling prices across the ten most popular car colors. Here are some observations:

*   **Wide Price Ranges:** For most popular colors, there's a very wide range of selling prices, indicated by the extended whiskers and numerous outliers. This suggests that factors other than color (like make, model, year, condition, etc.) are stronger drivers of price.
*   **Median Price Similarity:** The median selling prices (the line within the box) for many colors appear relatively similar, implying that for a typical car, color itself might not cause a dramatic difference in average price.
*   **Outliers Dominance:** The presence of many extreme outliers (individual points beyond the whiskers) indicates that very expensive cars can come in various colors, but these high-value cars significantly skew the upper end of the price distribution for those colors.
*   **Potential for High-Value Cars in Common Colors:** Even common colors like 'black', 'white', and 'silver' show very high selling price outliers, suggesting that luxury or high-performance vehicles are frequently available in these conventional shades.
*   **Impact on Readability:** The extensive presence of outliers makes it challenging to clearly see the interquartile range (IQR) and the typical price spread for each color. This indicates that removing these extreme outliers might provide a clearer view of the central tendency and variability for the majority of cars.
"""

